config/routes.rb
Neighbourfood::Application.routes.draw do
  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/meals/:id/buy' => 'orders#new', :as => 'buy'
  post '/meals/:id/buy' => 'orders#create'
  get '/orders' => 'orders#index'
  get '/about' => 'pages#about', :as => 'about'

  resources :users, :meals, :orders
  # , except => [:edit] do
  #   collection do
  #     get 'edit'
  #   end
  # end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  pickup     :datetime
#  servings   :integer          default(1)
#  user_id    :integer
#  meal_id    :integer
#  status     :string(255)
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  attr_accessible :servings, :user_id, :meal_id, :status, :rating, :pickup
  belongs_to :user
  belongs_to :meal

# Validation



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :check_if_logged_in

  def new
    @meals = Meal.where(:id => params[:id])
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
    @meals << @order.meal
  end

  def create
    @meal = Meal.find(params[:id])
    @order = Order.new params[:order]
    @order.status = "requested"
    @order.user = @auth
    @auth.orders << @order
    @meal.orders << @order
    UserMailer.new_meal_request(@order).deliver
    redirect_to orders_path
  end

  def index
    @orders_requested = Order.where(:status => "requested", :user_id => @auth.id)
    @orders_completed = Order.where(:status => "completed", :user_id => @auth.id)
    @orders_cancelled = Order.where(:status => "cancelled", :user_id => @auth.id)
  end

  def edit
    @order = Order.find(params[:id])
    @meals = []
    @meals << @order.meal
  end

  def update
    @order = Order.find(params[:id])
    @order.status = params[:status]
    @order.save
    redirect_to meals_path
  end

  private

  def check_if_logged_in
    redirect_to new_user_path unless @auth.present?
    flash[:notice] = "Almost there, you just need to sign up now or login if you already have an account" unless @auth.present?
  end

end

app/views/orders/_form.html.haml
.col-md-3.col-lg-3.col-sm-3.col-xs-3
  = form_for @order, :method => :post, :url => buy_path do |f|
    = f.label :servings
    = f.text_field :servings, :autofocus => true, :class => "form-control"
    %br/
    = f.datetime_select(:pickup, ampm: true, minute_step: 15)

    %br/
    = f.submit

app/views/orders/edit.html.haml
= render partial: "pages/preview"
.col-md-3.col-lg-3.col-sm-3.col-xs-3
  = form_for @order, :method => :put do |f|
    = f.label :servings
    = f.text_field :servings, :autofocus => true, :class => "form-control"
    = select_tag :status, options_for_select([['Requested', 'requested'], ['Completed', 'completed'], ['Cancel', 'cancelled']], params[:status])

    %br/
    = f.submit

app/views/orders/index.html.haml
.requested-order.alert.alert-success
  %h1
    Requested meals
  %table.col-lg-12.col-md-12.col-sm-12.col-xs-12
    %tr
      %th.second Meal
      %th.first Location
      %th.fifth Host
      %th.third Time
      %th.fourth Price
      %th.fifth Message
    - @orders_requested.each do |order|
      %tr
        %td.meal
          = link_to order.meal.name, meal_path(order.meal)
        %td.location
          = link_to order.meal.address, "http://maps.google.com/maps?&z=100&q=#{order.meal.address.to_s.gsub(" ","+")}"
        %td.host
          = link_to order.meal.user.fname, user_path(order.meal.user)
        %td.time
          = order.pickup.strftime("%I:%M%p")
          = order.meal.scheduled.strftime("%-d %b, %Y")
        %td.price
          $
          = number_with_precision(order.meal.price, :precision => 0)
        %td.message
          = link_to(raw('<span class="glyphicon glyphicon-envelope"></span>'), user_path(order.meal.user))
.completed-order
%h1
  Completed meals
%table.col-lg-12.col-md-12.col-sm-12.col-xs-12
  %tr
    %th.second Meal
    %th.first Location
    %th.fifth Host
    %th.third Time
    %th.sixth Rating
  - @orders_completed.each do |order|
    %tr
      %td.meal
        = link_to order.meal.name, meal_path(order.meal)
      %td.location
        = link_to order.meal.address, "http://maps.google.com/maps?&z=100&q=#{order.meal.address.to_s.gsub(" ","+")}"
      %td.host
        = link_to order.meal.user.fname, user_path(order.meal.user)
      %td.time
        = order.created_at.strftime("%I:%M%p %-d %b, %Y")
      %td.rating
        - if order.rating.present?
          = order.rating
        - else
          = rating link
.cancelled-order
%h1
  Cancelled meals
%table.col-lg-12.col-md-12.col-sm-12.col-xs-12
  %tr
    %th.second Meal
    %th.first Location
    %th.fifth Host
    %th.third Time
    %th.sixth Message
  - @orders_cancelled.each do |order|
    %tr
      %td.meal
        = link_to order.meal.name, meal_path(order.meal)
      %td.requested
        = order.status
      %td.location
        = link_to order.meal.address, "http://maps.google.com/maps?&z=100&q=#{order.meal.address.to_s.gsub(" ","+")}"
      %td.host
        = link_to order.meal.user.fname, user_path(order.meal.user)
      %td.time
        = order.created_at.strftime("%I:%M%p %-d %b, %Y")

app/views/orders/new.html.haml
= render partial: "pages/preview"
%br/
= render partial: "form"

app/views/orders/show.html.haml
%article.col-md-3.col-lg-3.col-sm-3.box.preview-meal
  = link_to(image_tag(@meal.image.url, :class=> "img-responsive"), meal_path(@meal))
  .preview-details
    %span.name
      = link_to @meal.name, meal_path(@meal)
    %span.price
      $
      = number_with_precision(@meal.price, :precision => 0)
    %p
      = @meal.address
    %p
      = @meal.user.username
%article.col-md-3.col-lg-3.col-sm-3
  %p{:class => "label"} Created at:
  = @order.created_at.strftime("%I:%M%p %-d %b, %Y")