config/routes.rb
Neighbourfood::Application.routes.draw do
  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/meals/:id/buy' => 'orders#new', :as => 'buy'
  post '/meals/:id/buy' => 'orders#create'
  get '/orders' => 'orders#index'
  get '/about' => 'pages#about', :as => 'about'

  resources :users, :meals, :orders
  # , except => [:edit] do
  #   collection do
  #     get 'edit'
  #   end
  # end
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  cuisine    :string(255)
#  address    :string(255)
#  price      :decimal(, )
#  servings   :integer
#  notes      :text
#  user_id    :integer
#  latitude   :float
#  longitude  :float
#  rating     :integer
#  scheduled  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Meal < ActiveRecord::Base
  attr_accessible :cuisine, :image, :name, :notes, :price, :user_id, :servings, :order_ids, :address, :rating, :scheduled
  has_many :orders
  belongs_to :user

  # Validations
  validate :scheduled_date_cannot_be_in_the_past
  validate

  # Geocoding
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  validates :image, :presence => true

  # Image Uploading
  mount_uploader :image, ImageUploader

  def scheduled_date_cannot_be_in_the_past
    errors.add(:scheduled, "time can't be in the past") if
      !scheduled.blank? and scheduled < Date.today
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_filter :check_if_logged_in, :except => [:show]

  def index
    @meals = Meal.where(:user_id => @auth.id)
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new params[:meal]
    @meal.user = @auth
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @meals = @meal.nearbys(10)
  end


  def edit
    @meal = Meal.find(params[:id])
    render :new
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.user = @auth
      if @meal.update_attributes(params[:meal])
        redirect_to root_path
      else
        render :new
      end
    end
  end

  def destroy
    meal = Meal.find(params[:id])
    if meal.user_id = @auth.id
      meal.destroy
      redirect_to root_path
    else
      flash[:notice] = "You are not authorised"
      redirect_to root_path
    end
  end

  private

  def check_if_logged_in
    redirect_to new_user_path unless @auth.present?
    flash[:notice] = "Almost there, you just need to sign up now or login if you already have an account" unless @auth.present?
  end

end

app/views/meals/_form.html.haml
= form_for @meal, :html => {:multipart => true} do |f|
  %div.input-group
    %span.input-group-addon.left
      = f.label :name
    = f.text_field :name, :autofocus => true, :class => "form-control"
  %br/
  %div.input-group
    - if @meal.image.url.present?
      %img{:src => @meal.image.url, :alt => ""}
    %br/
    %span.input-group-addon.left
      = f.label :image
    = f.file_field :image
  %br/
  %div.input-group.short-field
    %span.input-group-addon.left
      = f.label :cuisine
    = f.text_field :cuisine, :class => "form-control"
  %br/
  %div.input-group.short-field
    %span.input-group-addon.left
      = f.label :price
    = f.text_field :price, :class => "form-control"
    %span.input-group-addon .00
  %br/
  %div.input-group.short-field
    %span.input-group-addon.left
      = f.label :servings
    = f.text_field :servings, :class => "form-control"
  %br/
  %div.input-group
    %span.input-group-addon.left
      = f.label :scheduled, "Schedule: "
    = f.datetime_select(:scheduled, discard_year: true, default: Time.now, ampm: true, minute_step: 15, :class => "form-control")
  %br/
  %div.input-group
    %span.input-group-addon.left
      = f.label :address
    = f.text_field :address, :class => "form-control"
  %br/
  %div.input-group
    %span.input-group-addon.left
      = f.label :notes
    = f.text_area :notes, :class => "form-control", :rows=>"5"
  %br/
  == <input type="submit" value="#{ @meal.id.present?? 'Edit Meal' : 'Create Meal' }">

app/views/meals/index.html.haml
%h1 My meals
- @meals.each do |meal|
  .row.col-lg-12.col-md-12.col-sm-12.col-xs-12
    %h2
      = link_to meal.name, meal_path(meal), :target => "_blank"
    %table.col-lg-12.col-md-12.col-sm-12.col-xs-12
      %tr
        %th.first Status
        %th.second Buyer
        %th.third Time
        %th.second Message
      - meal.orders.each do |order|
        %tr
          %td{:class => "#{order.status}"}
            = link_to order.status.upcase, edit_order_path(order)
          %td.buyer
            = link_to order.user.username, user_path(order.user), :target => "_blank"
          %td.time
            = order.created_at.strftime("%I:%M%p %-d %b, %Y")
          %td.message
            = link_to(raw('<span class="glyphicon glyphicon-envelope"></span>'), user_path(order.meal.user))

app/views/meals/new.html.haml
- if @meal.errors.any?
  %ol
    - @meal.errors.full_messages.each do |msg|
      %li= msg

= render partial: "form"

app/views/meals/show.html.haml
.row
  / LEFT Column (meal details)
  .col-lg-4.col-md-4.about
    .panel.panel-primary
      .panel-heading
        %h1.panel-title
          = @meal.name
          %span.price
            $
            = number_with_precision(@meal.price, :precision => 0)
      %p.panel-address.panel-body
        = @meal.address
        - if @meal.user != @auth
          = link_to("Buy", buy_path, :class => 'buy price')
      %p.panel-body
        = @meal.notes
      %p.panel-body
        = link_to(image_tag("http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@meal.latitude}%2C#{@meal.longitude}", :class => "img-responsive"),"http://maps.google.com/maps?&z=100&q=#{@meal.address.to_s.gsub(" ","+")}", :target => 'new')
      - if @meal.user == @auth
        %p.panel-body.text-center
          = link_to("Edit", edit_meal_path(@meal), :class=>'control')
          = link_to("Delete", meal_path(@meal), :method => 'delete', :confirm => 'Are you sure?', :class=> 'control')
  / MIDDLE Column (meal picture)

  .col-lg-5.col-md-5.images
    %img{:src => "#{@meal.image.url}", :class => "img-responsive"}

  / RIGHT Column (chef details)

  .col-lg-3.col-md-3.chef
    .panel.panel-success
      .panel-heading
        %img.panel-title.text-center{:src => "#{@meal.user.image.thumb.url}"}
        %h2.panel-title.text-center
          = link_to("#{@meal.user.fname}",user_path(@meal.user))
      %p.panel-body
        = @meal.user.bio
      %ul.list-group
        %li.list-group-item
          Rating - feature coming soon
        %li.list-group-item
          Verification - feature coming soon

.row
  / BOTTOM Row (nearby meals)
  .col-lg-12.col-md-12.nearby
    %h3
      Nearby meals
    = render partial: "pages/preview"