config/routes.rb
Neighbourfood::Application.routes.draw do
  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/meals/:id/buy' => 'orders#new', :as => 'buy'
  post '/meals/:id/buy' => 'orders#create'
  get '/orders' => 'orders#index'
  get '/about' => 'pages#about', :as => 'about'

  resources :users, :meals, :orders
  # , except => [:edit] do
  #   collection do
  #     get 'edit'
  #   end
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighbourfood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Neighbourfood", root_path, :class => "navbar-brand" %>
      </div><!-- navbar-header -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if @auth.present? %>
            <li><%= link_to "Cook a Meal", new_meal_path %></li>
          <% if @auth.meals.length > 0 %>
          <li><%= link_to('My Meals', meals_path) %></li>
          <% end %>
          <% if @auth.orders.length > 0 %>
          <li><%= link_to('My Orders', orders_path) %></li>
          <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if @auth.present? %>
          <li><%= link_to('Edit User', edit_user_path(@auth)) %></li>
          <li><%= link_to('Logout ' + @auth.username, logout_path, :method => 'get', :confirm => 'Are you sure?') %></li>
          <% else %>
          <li><%= link_to("Sign Up", new_user_path) %></li>
          <%= render :partial => '/session/login' %>
          <% end %>
        </ul>
      </div><!--/.navbar-collapse -->
    </div><!-- container -->
  </div><!-- navbar -->

<% if flash[:notice].present? %>
  <div class='alert alert-info alert-dismissable col-12-lg col-12-md col-12-sm container text-center'>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong><%= flash[:notice] %></strong>
  </div>
<% end %>
<div class="container main-section">
  <%= yield %>
</div><!-- container main-section -->
<br>
<footer>
  <div class="container">
  <ul>
    <li><%= link_to("About", "/about") %></li>
    <li><%= link_to("Contact Us", "#") %></li>
    <li></li>
  </ul>
  <div class="social">
    <p>
      Facebook
      Twitter
      Pintrest
    </p>
    <p>
      Join our mailing list
    </p>
  </div><!-- social -->
</div>
</footer>


</body>
</html>